In [1]:
import numpy as np 
import pandas as pd

In [83]:
data = {
    'Name': ['john' , 'Anna' ,'Peter'],
    'Age':[28,34,29],
    'City':['New York','Paris','Berlin'],
    'Salary':[65000,70000,85000]
}
df =pd.DataFrame(data)
df

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   85000

In [84]:
df['Name']

0     john
1     Anna
2    Peter
Name: Name, dtype: str

In [85]:
df3=df[['Name' , 'City']]
df3

    Name      City
0   john  New York
1   Anna     Paris
2  Peter    Berlin

In [86]:
df["Work"]= ["doc","eng","doc"]

In [87]:
df

    Name  Age      City  Salary Work
0   john   28  New York   65000  doc
1   Anna   34     Paris   70000  eng
2  Peter   29    Berlin   85000  doc

In [88]:
df

    Name  Age      City  Salary Work
0   john   28  New York   65000  doc
1   Anna   34     Paris   70000  eng
2  Peter   29    Berlin   85000  doc

In [89]:
df.drop(['Age'],axis=1,inplace=True)

In [90]:
df

    Name      City  Salary Work
0   john  New York   65000  doc
1   Anna     Paris   70000  eng
2  Peter    Berlin   85000  doc

In [92]:
df.loc[[1,2]][['Name','City']]

    Name    City
1   Anna   Paris
2  Peter  Berlin